using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using static Dark_Cloud_Improved_Version.IsoBytes;

namespace Dark_Cloud_Improved_Version
{
    /// <summary>The monster sound library: every monster sound program of the dungeon sound sets in one archive file, so a floor
    /// can load the sounds of the species on it wherever the randomizer put them (tools/stubs/monster_bank.s builds the floor's
    /// monster bank from it as the floor loads).
    ///
    /// A monster sound id (601–2596) resolves through the ELF's static se_info table to a (program, note) of the monster bank —
    /// the `*_g` bank of the dungeon's sound set (`sound\set\snd{100 + dungeon}.snd`), on MIDI port 10. Each set's bank holds only
    /// its own natives' sounds, so a species placed elsewhere played nothing. A (program, note) is the same sound in every set
    /// that has it (all 170 shared ones match). A program carries up to three species' sounds, each on its own 30-note window,
    /// and each set only its natives' windows, so the library's unit is (program, window) — program × 4 + window — gathered across
    /// the eleven dungeon sets (<see cref="Gather"/>).
    ///
    /// The file (little-endian), its front read whole by the cave:
    ///   +0x0000 'DCMS', version 2, front bytes, front sectors
    ///   +0x0010 512 × 16 B by unit: front offset of its records (0 = absent), first sector and bytes (whole sectors) of its
    ///           samples, then split / sample-set / sample / VAG counts
    ///   +0x2010 176 × 2 units by species-table index (0xFFFF = none; <see cref="SpeciesUnits"/>)
    ///   +0x22D0 16 × 4 units by dungeon map (selectMapNo): units its own bank sounds that no species owns (0xFFFF = none) — sounds
    ///           the dungeon plays through its basic tables, kept in its floors' banks
    ///   +0x2350 176 × 8 B by species-table index: first sector and bytes of its Steve lines (0 bytes = none; <see cref="SteveBlocks"/>)
    ///   +0x28D0 each unit's records, 16-aligned: the program's 36-byte header and the unit's 20-byte splits, 6-byte sample sets,
    ///           42-byte samples and 8-byte VAG entries, indexed from 0 within the unit and the VAG offsets from its samples' start
    ///   then each unit's samples, then each distinct Steve block, sector-aligned. Steve's dungeon lines come one file a dungeon
    ///   (each only its natives'), so the cave writes each randomized floor's lines into Steve's buffer the same way.
    /// Under `sound\set\monlib.snd` — the dead backup copy `dun\monstor\e50a.chr_` renamed in place (docs/archive-dead-weight.md).</summary>
    internal static class MonsterSoundBake
    {
        private const string Dead = @"dun\monstor\e50a.chr_", Library = @"sound\set\monlib.snd";
        private const int FirstSet = 100, Sets = 11;                         // snd100–snd110: the dungeons' sets (Demon Shaft's five bands)
        private const int Units = 512, SpeciesRows = 176, KeepRows = 16, KeepCells = 4;
        private const int DirOff = 0x10, SpeciesOff = DirOff + Units * 16, KeepOff = SpeciesOff + SpeciesRows * 4, SteveOff = KeepOff + KeepRows * KeepCells * 2,
                          RecordsOff = SteveOff + SpeciesRows * 8;
        private const int SteveFirst = 4000, SteveLines = 10, SteveBlockMax = 6144;     // a species' lines: 4000 + name × 10 + 0..9
        private static readonly string[] SteveFiles =
            { "Steve01_1", "Steve02_1", "Steve03_1", "Steve04_1", "Steve05_1", "Steve06_1", "Steve07_1_1", "Steve07_2_1", "Steve07_3_1", "Steve07_4_1", "Steve07_5_1" };
        private const int NoteFirst = 20, NoteWindow = 30, Windows = 3;
        private const int ProgHeader = 36, SplitBytes = 20, SsetBytes = 6, SmplBytes = 42, VagiBytes = 8;
        private const ushort None = 0xFFFF, N = None;

        /// <summary>The sound units each species' sounds come from, by species-table index: program × 4 + window (a program carries up
        /// to three species' sounds, each on its own 30-note window: notes 20–49, 50–79, 80–109), N = none. Generated by
        /// tools/analysis/gen_species_sound_units.py from each species' script, model events and shot configs. The extension rows play
        /// Holy Gemron's script, so Holy Gemron's unit.</summary>
        internal static readonly ushort[,] SpeciesUnits =
        {
            { 53 * 4 + 0, N },   //   0 e01a
            { 53 * 4 + 0, N },   //   1 e03a
            { 57 * 4 + 0, N },   //   2 e05a
            { 58 * 4 + 0, N },   //   3 e06a
            { 59 * 4 + 0, N },   //   4 e07a
            { 60 * 4 + 0, N },   //   5 e08a
            { 61 * 4 + 0, N },   //   6 e09a
            { 62 * 4 + 0, N },   //   7 e10a
            { 63 * 4 + 0, N },   //   8 e11a
            { 64 * 4 + 0, N },   //   9 e12a
            { 66 * 4 + 0, N },   //  10 e14a
            { 67 * 4 + 0, N },   //  11 e15a
            { 68 * 4 + 0, N },   //  12 e16a
            { 69 * 4 + 0, N },   //  13 e17a
            { 70 * 4 + 0, N },   //  14 e18a
            { 71 * 4 + 0, N },   //  15 e19a
            { 72 * 4 + 0, N },   //  16 e20a
            { 73 * 4 + 0, N },   //  17 e21a
            { 74 * 4 + 0, N },   //  18 e22a
            { 75 * 4 + 0, N },   //  19 e23a
            { 76 * 4 + 0, N },   //  20 e24a
            { 77 * 4 + 0, N },   //  21 e25a
            { 78 * 4 + 0, N },   //  22 e26a
            { 79 * 4 + 0, N },   //  23 e27a
            { 80 * 4 + 0, N },   //  24 e28a
            { 82 * 4 + 0, N },   //  25 e30a
            { 83 * 4 + 0, N },   //  26 e31a
            { 84 * 4 + 0, N },   //  27 e32a
            { 85 * 4 + 0, N },   //  28 e33a
            { 86 * 4 + 0, N },   //  29 e34a
            { 87 * 4 + 0, N },   //  30 e35a
            { 88 * 4 + 0, N },   //  31 e36a
            { 89 * 4 + 0, N },   //  32 e37a
            { 90 * 4 + 0, N },   //  33 e38a
            { 91 * 4 + 0, N },   //  34 e39a
            { 92 * 4 + 0, N },   //  35 e40a
            { 94 * 4 + 0, N },   //  36 e42a
            { 95 * 4 + 0, N },   //  37 e43a
            { 96 * 4 + 0, N },   //  38 e44a
            { 97 * 4 + 0, N },   //  39 e45a
            { 98 * 4 + 0, N },   //  40 e46a
            { 99 * 4 + 0, N },   //  41 e47a
            { 100 * 4 + 0, N },   //  42 e48a
            { 101 * 4 + 0, N },   //  43 e49a
            { 102 * 4 + 0, N },   //  44 e50a
            { 103 * 4 + 0, N },   //  45 e51a
            { 104 * 4 + 0, N },   //  46 e52a
            { 107 * 4 + 0, N },   //  47 e55a
            { 108 * 4 + 0, N },   //  48 e56a
            { 109 * 4 + 0, N },   //  49 e57a
            { 110 * 4 + 0, N },   //  50 e58a
            { 111 * 4 + 0, N },   //  51 e59a
            { 56 * 4 + 0, N },   //  52 e60a
            { 65 * 4 + 0, N },   //  53 e61a
            { 72 * 4 + 1, N },   //  54 e62a
            { 58 * 4 + 1, N },   //  55 e63a
            { 82 * 4 + 1, N },   //  56 e64a
            { 82 * 4 + 2, N },   //  57 e65a
            { 64 * 4 + 1, N },   //  58 e66a
            { 63 * 4 + 1, N },   //  59 e67a
            { 63 * 4 + 2, N },   //  60 e68a
            { 83 * 4 + 1, N },   //  61 e69a
            { 84 * 4 + 1, N },   //  62 e70a
            { 75 * 4 + 1, N },   //  63 e71a
            { 76 * 4 + 1, N },   //  64 e72a
            { 111 * 4 + 1, N },   //  65 e73a
            { 111 * 4 + 2, N },   //  66 e74a
            { 95 * 4 + 1, N },   //  67 e75a
            { 54 * 4 + 0, N },   //  68 e76a
            { 81 * 4 + 0, N },   //  69 e77a
            { 86 * 4 + 1, N },   //  70 e78a
            { 87 * 4 + 1, N },   //  71 e79a
            { 86 * 4 + 2, N },   //  72 e80a
            { 87 * 4 + 2, N },   //  73 e81a
            { 90 * 4 + 1, N },   //  74 e82a
            { 91 * 4 + 1, N },   //  75 e83a
            { 114 * 4 + 0, N },   //  76 korinoya
            { 83 * 4 + 2, N },   //  77 e86a
            { 112 * 4 + 0, N },   //  78 c12a
            { 113 * 4 + 0, N },   //  79 c14a
            { 114 * 4 + 0, N },   //  80 c13a
            { 115 * 4 + 0, N },   //  81 c15a
            { 115 * 4 + 0, N },   //  82 c15b
            { 115 * 4 + 0, 116 * 4 + 0 },   //  83 c16a
            { 118 * 4 + 0, N },   //  84 c17a
            { 55 * 4 + 0, N },   //  85 c17b
            { 55 * 4 + 0, N },   //  86 c17c
            { N, N },   //  87 c17_hikari
            { N, N },   //  88 c17_kaze
            { N, N },   //  89 c17_beem
            { N, N },   //  90 c17_beem_s
            { 55 * 4 + 0, 116 * 4 + 0 },   //  91 e85a
            { N, N },   //  92 b3_reiki
            { 118 * 4 + 0, N },   //  93 c17_syougeki
            { 82 * 4 + 0, N },   //  94 e90a
            { 82 * 4 + 0, N },   //  95 e91a
            { 59 * 4 + 1, N },   //  96 e101a
            { 57 * 4 + 1, N },   //  97 e103a
            { 64 * 4 + 2, N },   //  98 e104a
            { 62 * 4 + 1, N },   //  99 e105a
            { 62 * 4 + 2, N },   // 100 e106a
            { 114 * 4 + 0, N },   // 101 baria
            { 114 * 4 + 0, N },   // 102 kori
            { 114 * 4 + 0, N },   // 103 i_meteo
            { 114 * 4 + 0, N },   // 104 i_tatumaki
            { 55 * 4 + 1, N },   // 105 e124a
            { 112 * 4 + 0, 120 * 4 + 0 },   // 106 c23a
            { N, N },   // 107 last_mc
            { N, N },   // 108 last_gw1
            { N, N },   // 109 c23_beem
            { N, N },   // 110 c23_beem_s
            { 105 * 4 + 0, N },   // 111 e111a
            { 54 * 4 + 2, N },   // 112 e108a
            { 108 * 4 + 0, N },   // 113 e125a
            { 92 * 4 + 0, N },   // 114 e126a
            { 82 * 4 + 0, N },   // 115 e127a
            { 62 * 4 + 0, N },   // 116 e128a
            { 53 * 4 + 0, N },   // 117 e129a
            { 84 * 4 + 1, N },   // 118 e130a
            { 102 * 4 + 0, N },   // 119 e131a
            { 98 * 4 + 0, N },   // 120 e132a
            { 105 * 4 + 1, N },   // 121 e112a
            { 53 * 4 + 1, N },   // 122 e119a
            { 78 * 4 + 0, N },   // 123 e133a
            { 81 * 4 + 0, N },   // 124 e134a
            { 59 * 4 + 1, N },   // 125 e135a
            { 73 * 4 + 0, N },   // 126 e136a
            { 82 * 4 + 1, N },   // 127 e137a
            { 97 * 4 + 0, N },   // 128 e138a
            { 80 * 4 + 0, N },   // 129 e139a
            { 89 * 4 + 1, N },   // 130 e109a
            { 88 * 4 + 1, N },   // 131 e110a
            { 105 * 4 + 2, N },   // 132 e113a
            { 54 * 4 + 1, N },   // 133 e116a
            { 56 * 4 + 0, N },   // 134 e140a
            { 82 * 4 + 0, N },   // 135 e141a
            { 95 * 4 + 1, N },   // 136 e142a
            { 76 * 4 + 0, N },   // 137 e143a
            { 99 * 4 + 0, N },   // 138 e144a
            { 58 * 4 + 1, N },   // 139 e145a
            { 79 * 4 + 0, N },   // 140 e146a
            { 89 * 4 + 1, N },   // 141 e109a
            { 88 * 4 + 1, N },   // 142 e110a
            { 106 * 4 + 0, N },   // 143 e114a
            { 53 * 4 + 2, N },   // 144 e118a
            { 95 * 4 + 0, N },   // 145 e149a
            { 96 * 4 + 0, N },   // 146 e150a
            { 101 * 4 + 0, N },   // 147 e151a
            { 75 * 4 + 1, N },   // 148 e152a
            { 63 * 4 + 2, N },   // 149 e153a
            { 77 * 4 + 0, N },   // 150 e154a
            { 76 * 4 + 1, N },   // 151 e155a
            { 89 * 4 + 1, N },   // 152 e109a
            { 88 * 4 + 1, N },   // 153 e110a
            { 106 * 4 + 1, N },   // 154 e115a
            { 55 * 4 + 1, N },   // 155 e117a
            { 65 * 4 + 0, N },   // 156 e158a
            { 54 * 4 + 0, N },   // 157 e159a
            { 57 * 4 + 1, N },   // 158 e160a
            { 100 * 4 + 0, N },   // 159 e161a
            { 103 * 4 + 0, N },   // 160 e162a
            { 85 * 4 + 0, N },   // 161 e163a
            { 107 * 4 + 0, N },   // 162 e164a
            { 89 * 4 + 1, N },   // 163 e109a
            { 88 * 4 + 1, N },   // 164 e110a
            { 121 * 4 + 0, N },   // 165 c21a
            { 121 * 4 + 0, N },   // 166 c22a
            { 106 * 4 + 1, N },   // 167 Bomb Gemron (Holy Gemron's script)
            { 106 * 4 + 1, N },   // 168 Crystal Gemron (Holy Gemron's script)
        };

        private sealed class Bank
        {
            internal byte[] Hd, Bd;
            internal int ProgOff, SsetOff, SmplOff, VagiOff;
            internal uint[] Prog, Sset, Smpl, Vagi;
            internal int[] VagStarts;
        }

        private static uint[] Table(byte[] hd, int off) =>
            Enumerable.Range(0, (int)U32(hd, off + 12) + 1).Select(i => U32(hd, off + 16 + i * 4)).ToArray();

        private static Bank ReadBank(byte[] hd, byte[] bd)
        {
            var b = new Bank { Hd = hd, Bd = bd };
            b.ProgOff = (int)U32(hd, 0x24); b.SsetOff = (int)U32(hd, 0x28); b.SmplOff = (int)U32(hd, 0x2C); b.VagiOff = (int)U32(hd, 0x30);
            b.Prog = Table(hd, b.ProgOff); b.Sset = Table(hd, b.SsetOff); b.Smpl = Table(hd, b.SmplOff); b.Vagi = Table(hd, b.VagiOff);
            b.VagStarts = b.Vagi.Where(o => o != uint.MaxValue).Select(o => (int)U32(hd, b.VagiOff + (int)o)).Distinct().OrderBy(a => a).ToArray();
            return b;
        }

        private static int VagSize(Bank b, int addr)
        {
            int i = Array.BinarySearch(b.VagStarts, addr);
            return (i + 1 < b.VagStarts.Length ? b.VagStarts[i + 1] : b.Bd.Length) - addr;
        }

        private static int Split(Bank b, int prog, int k) { int p = b.ProgOff + (int)b.Prog[prog]; return p + (int)U32(b.Hd, p) + k * b.Hd[p + 5]; }

        /// <summary>The 30-note window a split's first note falls in.</summary>
        private static int Window(byte lo) => lo < NoteFirst ? 0 : (lo - NoteFirst) / NoteWindow;

        /// <summary>One unit gathered across the sets — the union of every set's sounding splits of the program's window by note range,
        /// in note order and renumbered — with the program's header, its records indexed from 0 and its sample bytes (a sample several
        /// sets carry stored once). Null when no set sounds it.</summary>
        private static (byte[] records, byte[] samples, int nSplit, int nSset, int nSmpl, int nVagi)? Gather(List<Bank> banks, int prog, int window)
        {
            var chosen = new SortedDictionary<(byte lo, byte hi), (Bank bank, int at)>();
            byte[] header = null;
            foreach (var b in banks)
            {
                if (prog >= b.Prog.Length || b.Prog[prog] == uint.MaxValue) continue;
                int rec = b.ProgOff + (int)b.Prog[prog];
                if (U32(b.Hd, rec) != ProgHeader || b.Hd[rec + 5] != SplitBytes) throw new IOException($"program {prog}: unexpected record layout");
                header ??= b.Hd.AsSpan(rec, ProgHeader).ToArray();
                for (int k = 0; k < b.Hd[rec + 4]; k++)
                {
                    int at = Split(b, prog, k);
                    var key = (b.Hd[at + 2], b.Hd[at + 4]);
                    if (U16(b.Hd, at) != None && Window(b.Hd[at + 2]) == window && !chosen.ContainsKey(key)) chosen[key] = (b, at);
                }
            }
            if (chosen.Count == 0) return null;
            if (chosen.Count > 255) throw new IOException($"program {prog}: {chosen.Count} splits");
            var splits = new List<byte[]>(); var ssets = new List<byte[]>(); var smpls = new List<byte[]>(); var vagis = new List<byte[]>();
            var samples = new MemoryStream();
            var vagIndex = new Dictionary<string, int>();                      // a sample several sets carry is stored once (by its bytes)
            foreach (var (src, at) in chosen.Values)
            {
                byte[] split = src.Hd.AsSpan(at, SplitBytes).ToArray();
                byte[] ss = src.Hd.AsSpan(src.SsetOff + (int)src.Sset[U16(split, 0)], SsetBytes).ToArray();
                if (ss[3] != 1) throw new IOException($"program {prog}: a sample set of {ss[3]} samples");
                ushort smpl = U16(ss, 4);
                if (smpl != None)
                {
                    byte[] sm = src.Hd.AsSpan(src.SmplOff + (int)src.Smpl[smpl], SmplBytes).ToArray();
                    ushort vag = U16(sm, 0);
                    if (vag != None)
                    {
                        int addr = (int)U32(src.Hd, src.VagiOff + (int)src.Vagi[vag]);
                        byte[] va = src.Hd.AsSpan(src.VagiOff + (int)src.Vagi[vag], VagiBytes).ToArray();
                        byte[] bytes = src.Bd.AsSpan(addr, VagSize(src, addr)).ToArray();
                        string key = Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(bytes)) + Convert.ToHexString(va, 4, 4);
                        if (!vagIndex.TryGetValue(key, out int vi))
                        {
                            U32(va, 0, (uint)samples.Length);
                            samples.Write(bytes, 0, bytes.Length);
                            vi = vagis.Count; vagis.Add(va); vagIndex[key] = vi;
                        }
                        U16(sm, 0, (ushort)vi);
                    }
                    U16(ss, 4, (ushort)smpls.Count); smpls.Add(sm);
                }
                U16(split, 0, (ushort)ssets.Count); ssets.Add(ss);
                split[5] = (byte)splits.Count;
                splits.Add(split);
            }
            if (ssets.Count > 255 || smpls.Count > 255 || vagis.Count > 255) throw new IOException($"program {prog}: too many records");
            header[4] = (byte)splits.Count;
            var r = new MemoryStream();
            r.Write(header, 0, ProgHeader);
            foreach (var x in splits.Concat(ssets).Concat(smpls).Concat(vagis)) r.Write(x, 0, x.Length);
            return (r.ToArray(), samples.ToArray(), splits.Count, ssets.Count, smpls.Count, vagis.Count);
        }

        /// <summary>Whether <paramref name="b"/>'s own copy of the program sounds any note of the window.</summary>
        private static bool Sounds(Bank b, int prog, int window)
        {
            if (prog >= b.Prog.Length || b.Prog[prog] == uint.MaxValue) return false;
            int rec = b.ProgOff + (int)b.Prog[prog];
            for (int k = 0; k < b.Hd[rec + 4]; k++)
            {
                int at = Split(b, prog, k);
                if (U16(b.Hd, at) != None && Window(b.Hd[at + 2]) == window) return true;
            }
            return false;
        }

        /// <summary>Each species' Steve lines as a block (by species-table index): count, text halfwords, then (message id, the text's
        /// halfword offset in the block's text) a line, then the texts (each through its 0xFF01). A species' lines are messages
        /// 4000 + its name number × 10 + 0..9 of the dungeon Steve files that carry them (each file only its natives'); the
        /// extension species take their template's (Holy Gemron's) texts under their own ids.</summary>
        private static List<(int t, byte[] block)> SteveBlocks(Func<string, byte[]> read)
        {
            var files = SteveFiles.Select(n => read($@"dun\message\ww_mes\{n}.mes")).ToList();
            ushort[] Line(int id)                       // the first file whose entry for it has text (some carry an empty one at their text's end)
            {
                foreach (var f in files)
                {
                    int cnt = U16(f, 0), end = U16(f, 2);
                    for (int i = 0; i < cnt; i++)
                        if (U16(f, 4 + i * 4) == id && 2 * (cnt + U16(f, 6 + i * 4) + 1) < end) return MesTextBaker.MesExtract(f, id);
                }
                return null;
            }
            var blocks = new List<(int, byte[])>();
            foreach (var (t, own, source) in SteveSpecies())
            {
                var lines = Enumerable.Range(0, SteveLines).Select(k => (id: SteveFirst + own * SteveLines + k, words: Line(SteveFirst + source * SteveLines + k)))
                                      .Where(l => l.words != null).ToList();
                if (lines.Count == 0) continue;
                int words = lines.Sum(l => l.words.Length), head = 4 + lines.Count * 4;
                var b = new byte[head + words * 2];
                U16(b, 0, (ushort)lines.Count); U16(b, 2, (ushort)words);
                int at = 0;
                for (int k = 0; k < lines.Count; k++)
                {
                    U16(b, 4 + k * 4, (ushort)lines[k].id); U16(b, 6 + k * 4, (ushort)at);
                    foreach (ushort w in lines[k].words) { U16(b, head + at * 2, w); at++; }
                }
                if (b.Length > SteveBlockMax) throw new IOException($"species {t}: Steve lines of {b.Length:N0} B past {SteveBlockMax:N0}");
                blocks.Add((t, b));
            }
            return blocks;
        }

        /// <summary>Species-table index → (its name number, the name number whose Steve texts it takes).</summary>
        private static IEnumerable<(int t, int own, int source)> SteveSpecies()
        {
            foreach (var kv in EnemySpecies.All)
            {
                if (kv.Value.TableIndex is not int t || t >= SpeciesRows) continue;
                int own = kv.Value.Id, source = t >= EnemySpeciesTable.VanillaCount ? TemplateName(t) : own;
                yield return (t, own, source);
            }
        }

        /// <summary>The name number of the vanilla species an extension row is built on (SpeciesRows).</summary>
        private static int TemplateName(int t)
        {
            foreach (var (species, template, _, _, _) in Dark_Cloud_Improved_Version.SpeciesRows.Rows)
                if (species.TableIndex == t) return EnemySpecies.All[template].Id;
            return EnemySpecies.All[t].Id;
        }

        internal static byte[] Build(Func<string, byte[]> read)
        {
            var banks = new List<Bank>(); var setPrograms = new List<int[]>();
            for (int s = 0; s < Sets; s++)
            {
                var pack = ChrPack.Parse(read($@"sound\set\snd{FirstSet + s}.snd"));
                var g = pack.Records.First(r => r.Name.EndsWith("_g.hd", StringComparison.OrdinalIgnoreCase));
                var bank = ReadBank(g.Payload, pack.Require(g.Name.Substring(0, g.Name.Length - 2) + "bd").Payload);
                banks.Add(bank);
                setPrograms.Add(Enumerable.Range(0, bank.Prog.Length).Where(p => bank.Prog[p] != uint.MaxValue).ToArray());
            }
            var front = new MemoryStream(); front.Write(new byte[RecordsOff], 0, RecordsOff);
            var blocks = new List<(int unit, byte[] bytes)>();
            var dir = new byte[Units * 16];
            var present = new HashSet<int>();
            foreach (int prog in setPrograms.SelectMany(p => p).Distinct().OrderBy(p => p))
                for (int window = 0; window < Windows; window++)
                {
                    int unit = prog * 4 + window;
                    if (unit >= Units) throw new IOException($"program {prog} past the directory");
                    var gathered = Gather(banks, prog, window);
                    if (gathered == null) continue;
                    var (records, samples, nSplit, nSset, nSmpl, nVagi) = gathered.Value;
                    front.Position = Align16((int)front.Length); front.SetLength(front.Position);
                    U32(dir, unit * 16, (uint)front.Position);
                    front.Write(records, 0, records.Length);
                    dir[unit * 16 + 12] = (byte)nSplit; dir[unit * 16 + 13] = (byte)nSset; dir[unit * 16 + 14] = (byte)nSmpl; dir[unit * 16 + 15] = (byte)nVagi;
                    blocks.Add((unit, samples)); present.Add(unit);
                }
            byte[] head = front.ToArray();
            int frontBytes = head.Length, frontSectors = (int)(Align(frontBytes) / SectorBytes);
            var file = new MemoryStream(); file.Write(head, 0, head.Length); file.SetLength(Align(file.Length));
            foreach (var (unit, bytes) in blocks)
            {
                file.Position = file.Length;
                U32(dir, unit * 16 + 4, (uint)(file.Position / SectorBytes));
                U32(dir, unit * 16 + 8, (uint)Align(bytes.Length));
                file.Write(bytes, 0, bytes.Length); file.SetLength(Align(file.Length));
            }
            var steveDir = new byte[SpeciesRows * 8];
            var steveAt = new Dictionary<string, (uint sector, uint bytes)>();
            var steve = SteveBlocks(read);
            foreach (var (t, block) in steve)
            {
                string key = Convert.ToHexString(block);
                if (!steveAt.TryGetValue(key, out var at))
                {
                    file.Position = file.Length;
                    at = ((uint)(file.Position / SectorBytes), (uint)Align(block.Length));
                    file.Write(block, 0, block.Length); file.SetLength(Align(file.Length));
                    steveAt[key] = at;
                }
                U32(steveDir, t * 8, at.sector); U32(steveDir, t * 8 + 4, at.bytes);
            }
            byte[] o = file.ToArray();
            steveDir.CopyTo(o, SteveOff);
            System.Text.Encoding.ASCII.GetBytes("DCMS").CopyTo(o, 0);
            U32(o, 4, 2); U32(o, 8, (uint)frontBytes); U32(o, 12, (uint)frontSectors);
            dir.CopyTo(o, DirOff);
            for (int t = 0; t < SpeciesRows; t++)
                for (int c = 0; c < 2; c++) U16(o, SpeciesOff + t * 4 + c * 2, t < SpeciesUnits.GetLength(0) ? SpeciesUnits[t, c] : None);
            var owned = new HashSet<int>(Enumerable.Range(0, SpeciesUnits.GetLength(0)).SelectMany(t => new[] { (int)SpeciesUnits[t, 0], SpeciesUnits[t, 1] }));
            for (int m = 0; m < KeepRows; m++)
            {
                var keep = m < Sets
                    ? setPrograms[m].SelectMany(p => Enumerable.Range(0, Windows).Where(w => Sounds(banks[m], p, w)).Select(w => p * 4 + w))
                                    .Where(u => present.Contains(u) && !owned.Contains(u)).ToArray()
                    : Array.Empty<int>();
                if (keep.Length > KeepCells) throw new IOException($"dungeon map {m}: {keep.Length} kept units");
                for (int c = 0; c < KeepCells; c++) U16(o, KeepOff + m * KeepCells * 2 + c * 2, c < keep.Length ? (ushort)keep[c] : None);
            }
            return o;
        }

        internal static void Run(IsoArchive arc, Action<string> log)
        {
            if (!arc.Has(Library))
            {
                if (!arc.Has(Dead)) throw new IOException($"neither {Library} nor the dead entry {Dead} is in the archive");
                arc.Rename(Dead, Library);
            }
            byte[] lib = Build(arc.Read);
            arc.Redirect(Library, lib);
            log($"{Library}: {lib.Length:N0} B, front {U32(lib, 8):N0} B");
        }
    }
}
