#!/usr/bin/env python3
"""Brownboo (s04) CAMERA collision — the SHIPPED custom obj56 and the iwa01 hull's authoring inputs.

s04g01_v is the town's CAMERA collision (LoadMapObject @0x19B790 fills the camera frame +0xDC from part-header
slot +0x20 — the slot every other town names `_c`; Brownboo labels it `_v`). Node `v` (404 tris) is the terrain
camera hull (untouched); node `obj56` (900 tris) carries the structures. The one shipped edit
(iwa01_ring_obj56, consumed by brownboo_collision_builder -> patch_iso_town_collision): the lumpy iwa01
tunnel-rock selection is REPLACED by the frozen CSG hull (brownboo_rock_hull_data.IWA01_HULL, regenerated by
tools/brownboo_rock_hull_builder.py from the _IWA01_* authoring tris + _collar_pairs kept here).

The 2026-08 experiments (central-cylinder simplification, per-leg s04h01 nodes, rock shell prisms, tightened
house cylinders) were all REVERTED and their code deleted 2026-09 — recoverable via git.

Run standalone for a summary: python3 tools/brownboo_camera_collision.py
"""
import math
import os, re, struct, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import scene_placed
from extract_scene_mesh import load_scene, xform, read_verts, read_tris
from georama_collision import parse_coll_mdt
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "iso_patch", "collision"))
from collision_geom import triangle_normal, kd_split


def tri_key_tenth(t):
    return tuple(sorted(tuple(round(c, 1) for c in p) for p in t))


def vanilla_v_nodes(scn=None):
    """[(node_name, tris)] of s04g01_v (world == local: s04g01's mapinfo placement is the origin).
    scn: scene.scn BYTES to decode from (e.g. read out of a patched ISO); None = the local extraction
    (needs DC1_DATA_DIR — the viewer/authoring path)."""
    if scn is None:
        scn = load_scene('gedit/s04/scene.scn')
    DIR = scene_placed.scn_directory_map(scn)
    off, size = DIR['s04g01']
    sub = scn[off:off + size]
    m = next(re.finditer(rb's04g01_v\.mds\x00', sub), None)
    if m is None:
        return []
    vo = struct.unpack_from('<I', sub, m.end() + 3)[0]
    mds = off + vo
    nodes, wm = scene_placed._accum(scn, mds)
    out = []
    for i, (nn, mo, par, mat) in enumerate(nodes):
        if mo == 0:
            continue
        fo = next((c for c in (mo, mds + mo) if 0 < c < len(scn) and scn[c:c + 3] == b'MDT'), None)
        if not fo:
            continue
        M = wm(i)
        tris = [[list(xform(M, a)), list(xform(M, b)), list(xform(M, c))] for a, b, c in parse_coll_mdt(scn, fo)]
        if tris:
            out.append((nn, tris))
    return out


def parse_tri_block(raw):
    """'x,y,z,x,y,z,x,y,z' per line (blank lines skipped) -> [[v0,v1,v2], ...]."""
    out = []
    for ln in raw.strip().splitlines():
        if ln.strip():
            xs = [float(x) for x in ln.split(',')]
            out.append([xs[0:3], xs[3:6], xs[6:9]])
    return out


# ---- rock selections: obj56 tris fully inside a rock VISUAL's padded bbox, excluding r<=83 of the
#      origin (central-cylinder guard). Used by the iwa01 hull replacement below.
_ROCK_SEL = {                     # visual-node bbox (from iwa01/02/03__s) + 8 pad, baked as literals
    'iwa01': (-212.1, -81.5, -96.1, 34.0),
    'iwa02': (-55.7, 69.7, 126.6, 182.3),
    'iwa03': (177.1, 252.2, -88.9, -9.9),
}


def _rock_sel_tris(obj56, box):
    x0, x1, z0, z1 = box
    return [t for t in obj56 if all(x0 <= p[0] <= x1 and z0 <= p[2] <= z1 for p in t)
            and all(math.hypot(p[0], p[2]) > 83 for p in t)]


# ---- IWA01 tunnel-rock camera hull (2026-08): REPLACES the lumpy obj56 iwa01 selection with a smooth
#      circle wall centred on the ROCK, keeping the native tunnel interior so the camera can pass through,
#      and extending the two entrance collars OUTWARD ALONG THEIR OWN TAPER to meet the circle (seamless
#      funnels that catch the camera at the wide circle opening and channel it into the narrow native mouth).
#      Pure REPLACE: iwa01_selection removed, this added. Base y-15 (clips the in-water base — approved).
_IWA01_TOP = 92.0
_IWA01_BOT = -15.0
_IWA01_PAD = 4.0




_IWA01_WEST = parse_tri_block("""
-167.92,29.7,-52.47, -161.65,34.59,-41.16, -169.79,40.38,-42.83
-161.65,34.59,-41.16, -172.38,40.35,-31.57, -169.79,40.38,-42.83
-161.65,34.59,-41.16, -164.94,34.49,-29.88, -172.38,40.35,-31.57
-172.38,40.35,-31.57, -164.94,34.49,-29.88, -166.39,28.13,-23.63
-172.38,40.35,-31.57, -166.39,28.13,-23.63, -174.07,29.7,-23.15
-174.07,29.7,-23.15, -166.39,28.13,-23.63, -170.04,16.08,-23.01
-174.07,29.7,-23.15, -170.04,16.08,-23.01, -177.77,17.67,-22.52
-177.77,17.67,-22.52, -170.04,16.08,-23.01, -167.96,8,-28.08
-177.77,17.67,-22.52, -167.96,8,-28.08, -182.73,6.74,-30.49
-182.73,6.74,-30.49, -167.96,8,-28.08, -163.51,8,-47.58
-182.73,6.74,-30.49, -163.51,8,-47.58, -178.53,6.89,-51.9
-178.53,6.89,-51.9, -163.51,8,-47.58, -163.52,16.01,-51.6
-178.53,6.89,-51.9, -163.52,16.01,-51.6, -171.69,17.54,-55.71
-171.69,17.54,-55.71, -159.62,28.25,-48.39, -167.92,29.7,-52.47
-171.69,17.54,-55.71, -163.52,16.01,-51.6, -159.62,28.25,-48.39
-167.92,29.7,-52.47, -159.62,28.25,-48.39, -161.65,34.59,-41.16
""")
_IWA01_EAST = parse_tri_block("""
-123.04,38.75,-36.34, -125.26,38.74,-25.25, -131.68,35.04,-26.03
-123.04,38.75,-36.34, -131.68,35.04,-26.03, -128.7,35.07,-37.26
-123.04,38.75,-36.34, -128.7,35.07,-37.26, -126.84,28.52,-43.55
-123.04,38.75,-36.34, -126.84,28.52,-43.55, -120.34,28.3,-44.21
-120.34,28.3,-44.21, -122.29,15.91,-44.15, -115.44,16.18,-44.75
-120.34,28.3,-44.21, -126.84,28.52,-43.55, -122.29,15.91,-44.15
-115.44,16.18,-44.75, -124.52,8,-38.68, -112.93,5.12,-37.63
-115.44,16.18,-44.75, -122.29,15.91,-44.15, -124.52,8,-38.68
-112.93,5.12,-37.63, -124.52,8,-38.68, -128.97,8,-19.18
-112.93,5.12,-37.63, -128.97,8,-19.18, -117.04,4.94,-16.3
-129.17,15.9,-16.07, -117.04,4.94,-16.3, -128.97,8,-19.18
-129.17,15.9,-16.07, -119.65,16.18,-11.88, -117.04,4.94,-16.3
-133.43,28.46,-19.13, -123.62,28.93,-15.17, -119.65,16.18,-11.88
-133.43,28.46,-19.13, -119.65,16.18,-11.88, -129.17,15.9,-16.07
-131.68,35.04,-26.03, -125.26,38.74,-25.25, -123.62,28.93,-15.17
-131.68,35.04,-26.03, -123.62,28.93,-15.17, -133.43,28.46,-19.13
""")
_IWA01_INTERIOR = parse_tri_block("""
-128.7,35.07,-37.26, -131.68,35.04,-26.03, -164.94,34.49,-29.88
-128.7,35.07,-37.26, -164.94,34.49,-29.88, -161.65,34.59,-41.16
-159.62,28.25,-48.39, -128.7,35.07,-37.26, -161.65,34.59,-41.16
-159.62,28.25,-48.39, -126.84,28.52,-43.55, -128.7,35.07,-37.26
-164.94,34.49,-29.88, -131.68,35.04,-26.03, -133.43,28.46,-19.13
-164.94,34.49,-29.88, -133.43,28.46,-19.13, -166.39,28.13,-23.63
-133.43,28.46,-19.13, -170.04,16.08,-23.01, -166.39,28.13,-23.63
-133.43,28.46,-19.13, -129.17,15.9,-16.07, -170.04,16.08,-23.01
-128.97,8,-19.18, -170.04,16.08,-23.01, -129.17,15.9,-16.07
-128.97,8,-19.18, -167.96,8,-28.08, -170.04,16.08,-23.01
-124.52,8,-38.68, -167.96,8,-28.08, -128.97,8,-19.18
-124.52,8,-38.68, -163.51,8,-47.58, -167.96,8,-28.08
-163.51,8,-47.58, -124.52,8,-38.68, -122.29,15.91,-44.15
-163.51,8,-47.58, -122.29,15.91,-44.15, -163.52,16.01,-51.6
-122.29,15.91,-44.15, -159.62,28.25,-48.39, -163.52,16.01,-51.6
-122.29,15.91,-44.15, -126.84,28.52,-43.55, -159.62,28.25,-48.39
""")

# vanilla obj56 tris inside the _ROCK_SEL['iwa01'] bbox that must SURVIVE the removal: the low walkway/
# bank strip running through and past both tunnel mouths (y~9-14 path collision + its water-side skirts).
# Matched by centroid (tolerance), not tri_key_tenth — one tri's coords land on a 0.05 rounding boundary.
_IWA01_KEEP = parse_tri_block("""
-87.73,9,29.73, -92.08,-10,10.68, -87.73,-10,29.73
-87.73,9,29.73, -92.08,12,10.68, -92.08,-10,10.68
-92.08,12,10.68, -89.97,-10,-10.28, -92.08,-10,10.68
-92.08,12,10.68, -89.97,14,-10.28, -89.97,-10,-10.28
-89.97,-10,-10.28, -89.97,14,-10.28, -110.47,11,-11.73
-110.47,11,-11.73, -94.15,-15,-10.14, -89.97,-10,-10.28
-106.02,11,-31.23, -85.52,14,-29.78, -85.52,-10,-29.78
-85.52,-10,-29.78, -89.49,-15,-33.18, -106.02,11,-31.23
-89.97,14,-10.28, -85.52,14,-29.78, -106.02,11,-31.23
-89.97,14,-10.28, -106.02,11,-31.23, -110.47,11,-11.73
-110.47,11,-11.73, -106.02,11,-31.23, -124.52,10,-38.68
-110.47,11,-11.73, -124.52,10,-38.68, -128.97,10,-19.18
-128.97,10,-19.18, -144.01,10,-43.13, -148.46,10,-23.63
-128.97,10,-19.18, -124.52,10,-38.68, -144.01,10,-43.13
-148.46,10,-23.63, -163.51,10,-47.58, -167.96,10,-28.08
-148.46,10,-23.63, -144.01,10,-43.13, -163.51,10,-47.58
-167.96,10,-28.08, -163.51,10,-47.58, -184.01,9,-49.03
-167.96,10,-28.08, -184.01,9,-49.03, -188.46,9,-29.53
-188.46,9,-29.53, -202.51,11,-55.48, -206.96,11,-35.98
-188.46,9,-29.53, -184.01,9,-49.03, -202.51,11,-55.48
-188.46,9,-29.53, -206.96,11,-35.98, -206.96,-10,-35.98
-202.51,-10,-55.48, -202.51,11,-55.48, -184.01,9,-49.03
-206.96,-10,-35.98, -204.1,-15,-33.79, -188.46,9,-29.53
-184.01,9,-49.03, -200.13,-15,-57.17, -202.51,-10,-55.48
""")


def _iwa01_keep_match(tris):
    """Subset of `tris` whose centroid is within 0.2 of an _IWA01_KEEP centroid."""
    cen = lambda t: [sum(p[i] for p in t) / 3 for i in range(3)]
    kc = [cen(t) for t in _IWA01_KEEP]
    return [t for t in tris if any(max(abs(a - b) for a, b in zip(cen(t), c)) < 0.2 for c in kc)]


def vec3(a, o, b):
    return [a[i] + o * b[i] for i in range(3)]

def _dot(a, b): return sum(a[i] * b[i] for i in range(3))
def _sub(a, b): return [a[i] - b[i] for i in range(3)]
def _cross(a, b): return [a[1]*b[2]-a[2]*b[1], a[2]*b[0]-a[0]*b[2], a[0]*b[1]-a[1]*b[0]]
def _norm(a):
    L = math.sqrt(_dot(a, a)) or 1.0
    return [c / L for c in a]


def _iwa01_rock_sil2d(nb=60, ny=18, ylo=-16.0, yhi=92.0, rmin=42.0):
    """2D (bearing x height) silhouette of the visual rock's OUTER face about the hull-circle centre:
    grid[b][j] = max r of rock verts in that (360/nb-degree, (yhi-ylo)/ny-unit) cell, above water (y>0)
    and outside r>=rmin (excluding the tunnel-interior walls, which would wrongly wall off the mouth).
    0.0 where empty. Lets the funnel hug the actual rock face height-aware instead of the global bulge."""
    from extract_scene_mesh import extract_mesh
    v, _ = extract_mesh(load_scene('gedit/s04/scene.scn'))['iwa01__s']
    cx = (min(p[0] for p in v) + max(p[0] for p in v)) / 2
    cz = (min(p[2] for p in v) + max(p[2] for p in v)) / 2
    grid = [[0.0] * ny for _ in range(nb)]
    for p in v:
        r = math.hypot(p[0] - cx, p[2] - cz)
        if p[1] > 0 and r >= rmin:
            b = int((math.degrees(math.atan2(p[2] - cz, p[0] - cx)) % 360) // (360 / nb))
            j = min(ny - 1, max(0, int((p[1] - ylo) / ((yhi - ylo) / ny))))
            grid[b][j] = max(grid[b][j], r)
    return cx, cz, grid, (nb, ny, ylo, yhi)


def _iwa01_visual_circle():
    """(cx, cz, R): circle centred on the VISUAL rock (iwa01__s), radius enclosing its ABOVE-WATER xz
    silhouette + pad. The rock's widest spread (r~61) is all submerged base — clipping that is fine (the
    camera never dips there) and sizing on the y>0 silhouette (r~50) keeps the hull ~11 units narrower."""
    from extract_scene_mesh import extract_mesh
    v, _ = extract_mesh(load_scene('gedit/s04/scene.scn'))['iwa01__s']
    cx = (min(p[0] for p in v) + max(p[0] for p in v)) / 2
    cz = (min(p[2] for p in v) + max(p[2] for p in v)) / 2
    R = max(math.hypot(p[0] - cx, p[2] - cz) for p in v if p[1] > 0) + _IWA01_PAD
    return cx, cz, R


def _collar_pairs(ent, ivk):
    """Ordered [(outer, inner)] around the tunnel cross-section: inner = verts shared with the interior,
    outer = the flared rim; each outer paired to the nearest inner it shares a triangle with; ordered by
    angle around the tunnel axis (inner-centroid -> outer-centroid)."""
    ev = {}
    for t in ent:
        for p in t:
            ev[tuple(round(c, 2) for c in p)] = p
    inner = {k: v for k, v in ev.items() if tuple(round(c, 2) for c in v) in ivk}
    outer = {k: v for k, v in ev.items() if k not in inner}
    pair = {}
    for ok, ov in outer.items():
        cand = set()
        for t in ent:
            tk = [tuple(round(c, 2) for c in p) for p in t]
            if ok in tk:
                cand |= {k for k in tk if k in inner}
        if cand:
            pair[ok] = min(cand, key=lambda ck: math.dist(ov, inner[ck]))
    ic = [sum(inner[k][i] for k in inner) / len(inner) for i in range(3)]
    oc = [sum(outer[k][i] for k in outer) / len(outer) for i in range(3)]
    axis = _norm(_sub(oc, ic))
    u = _norm(_cross(axis, [0, 1, 0]))
    w = _cross(axis, u)
    ang = lambda v: math.atan2(_dot(_sub(v, oc), w), _dot(_sub(v, oc), u))
    order = sorted((k for k in outer if k in pair), key=lambda k: ang(outer[k]))
    return [(outer[k], inner[pair[k]]) for k in order]


def _extend_to_circle(o, iv, cx, cz, R):
    """Continue the collar taper (iv -> o) until the xz-radius from (cx,cz) reaches R (the circle)."""
    d = _sub(o, iv)
    ox, oz, dx, dz = o[0] - cx, o[2] - cz, d[0], d[2]
    a = dx * dx + dz * dz
    b = 2 * (ox * dx + oz * dz)
    c = ox * ox + oz * oz - R * R
    disc = b * b - 4 * a * c
    if a < 1e-9 or disc < 0:
        return None
    t = (-b + math.sqrt(disc)) / (2 * a)
    return vec3(o, t, d)


def _iwa01_build():
    """The iwa01 camera hull: the cylinder shell around the rock MINUS the flared tunnel cutter (exact
    CSG difference), top & bottom caps stripped. Authored in tools/brownboo_rock_hull_builder.py and FROZEN to
    tools/brownboo_rock_hull_data.py as a plain tri literal, so the bake needs no CSG deps. Re-run that generator
    (needs trimesh+manifold3d) to regenerate the frozen data after tweaking the funnel/cylinder params."""
    from brownboo_rock_hull_data import IWA01_HULL
    return [[list(p) for p in t] for t in IWA01_HULL]


def iwa01_ring_tris():
    return _iwa01_build()


def iwa01_ring_obj56(scn=None):
    """Vanilla obj56 with the lumpy iwa01 selection REPLACED by the circle-hull build. The walkway/bank
    strip through the tunnel (_IWA01_KEEP) survives the bbox removal — the hull doesn't cover it."""
    obj56 = next(t for nn, t in vanilla_v_nodes(scn) if nn == 'obj56')
    sel = _rock_sel_tris(obj56, _ROCK_SEL['iwa01'])
    selk = set(tri_key_tenth(t) for t in sel) - set(tri_key_tenth(t) for t in _iwa01_keep_match(sel))
    keep = [t for t in obj56 if tri_key_tenth(t) not in selk]
    return [list(map(list, t)) for t in keep] + _iwa01_build()


if __name__ == '__main__':
    van = next((tris for nn, tris in vanilla_v_nodes() if nn == 'obj56'), [])
    shipped = iwa01_ring_obj56()
    print(f'obj56: vanilla {len(van)} -> shipped {len(shipped)} (iwa01 rock selection replaced by the CSG hull)')
