#!/usr/bin/env python3
"""Emit a Blender script showing Priscleen's OWN DC2 rig — its native 52-bone skeleton, both body meshes
(skin1 + skin2) with their AUTHORED vertex weights, and its 3 existing motions baked as Actions.

Unlike build_blender_rig.py (which borrows a DC1 donor skeleton and re-weights → stretching), this uses
Priscleen's real skeleton + real .wgt weights, so the mesh deforms exactly as the game intends. The point:
view the native rig, then hand-animate the 4 missing DC1 motions on THIS skeleton (or have them approximated
from the DC1 motions) and export back.

Source: DC2 sg/fish/f19a.chr (via the DC2 archive). Output: dc2/blender/priscleen_native.py
"""
import os, sys, struct, re
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "tools"))
from dc2_archive import read_file
from extract_scene_mesh import parse_mds, read_tris
from build_blender_rig import parse_chr, skeleton, motions

OUT = os.path.join(os.path.dirname(__file__), "blender", "priscleen_native.py")

def mesh_of(mds, name):
    mo = next((mo for nm, mo, _ in parse_mds(mds, 0) if nm == name and mds[mo:mo+3] == b"MDT"), None)
    if mo is None: return [], []
    vc = struct.unpack_from("<I", mds, mo+0xc)[0]; vo = mo + struct.unpack_from("<I", mds, mo+0x10)[0]
    verts = [list(struct.unpack_from("<3f", mds, vo+i*0x10)) for i in range(vc)]
    return verts, [list(t) for t in read_tris(mds, mo)]

def parse_wgt(wgt, frames):
    """skinFrameName -> per-vertex [[boneIdx, weight0to1], ...] using the .wgt node layout
    (h[0]=skin frame, h[1]=bone frame, entries: [0]=vertexIndex, +0x10=weight 0-100)."""
    name = {i: nm for i, (nm, pa, loc) in enumerate(frames)}
    out = {}
    o = 0
    while o + 0x20 <= len(wgt):
        h = struct.unpack_from("<8I", wgt, o); skinf, bone, cnt = h[0], h[1], h[4]
        d = out.setdefault(name.get(skinf, str(skinf)), {})
        for k in range(cnt):
            base = o+0x20+k*0x20
            vi = struct.unpack_from("<I", wgt, base)[0]
            w = struct.unpack_from("<f", wgt, base+0x10)[0]
            d.setdefault(vi, []).append([bone, w/100.0])
        if h[5] == 0: break
        o += h[5]
    return out

def dc2_keys(cfg):
    """Parse DC2 'KEY "name", start, end, weight;' lines into [(start, end, label)]."""
    keys = []
    for i, m in enumerate(re.finditer(r'KEY\s+"[^"]*",\s*(\d+),\s*(\d+),\s*[\d.]+', cfg)):
        keys.append((int(m.group(1)), int(m.group(2)), f"motion{i}"))
    return keys

def main():
    chr = dict(parse_chr(read_file("sg/fish/f19a.chr")))
    mds = chr["f19a.mds"]; cfg = chr["info.cfg"].decode("latin1", "replace")
    frames, world = skeleton(mds)
    bones = [{"name": f"{i}_{nm}", "parent": pa, "local": loc} for i, (nm, pa, loc) in enumerate(frames)]
    _, rot, trans = motions(chr["f19a.mot"], "")     # tracks only; keys come from DC2 cfg below
    keys = dc2_keys(cfg)
    wmap = parse_wgt(chr["f19a.wgt"], frames)

    meshes = []
    for mname in ("skin1", "skin2"):
        verts, tris = mesh_of(mds, mname)
        w = wmap.get(mname, {})
        weights = [w.get(vi, []) for vi in range(len(verts))]
        meshes.append({"name": mname, "verts": verts, "tris": tris, "weights": weights})

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("# AUTO-GENERATED by dc2/build_priscleen_native.py — Priscleen's OWN DC2 rig.\n")
        f.write("# Open in Blender's Text editor and Run. Native skeleton + native weights + 3 motions.\n")
        f.write("import bpy, math\nfrom mathutils import Vector, Quaternion, Matrix\n\n")
        f.write("BONES = %r\n" % bones)
        f.write("MESHES = %r\n" % meshes)
        f.write("KEYS  = %r\n" % keys)
        # DC .mot quaternions use the opposite handedness from mathutils — conjugate (w,x,y,z)->(w,-x,-y,-z)
        # so the keyframed pose reproduces the .mds/.bbp bind (verified: worst rotation diff 2.0 -> 0.0).
        f.write("ROT_TRACKS   = %r\n" % {k: [(t, [q[0], -q[1], -q[2], -q[3]]) for t, q in v] for k, v in rot.items()})
        f.write("TRANS_TRACKS = %r\n" % {k: [(t, list(q)) for t, q in v] for k, v in trans.items()})
        f.write(BODY)
    nv = sum(len(m["verts"]) for m in meshes)
    nw = sum(1 for m in meshes for wl in m["weights"] if wl)
    print(f"wrote {OUT}: {len(bones)} bones, {len(meshes)} meshes ({nv}v, {nw} weighted), "
          f"{len(keys)} motions, {len(rot)} rot / {len(trans)} trans tracks")

BODY = r'''
UP = Matrix.Rotation(math.radians(90), 4, 'X')
I4 = Matrix.Identity(4)

def to_mat(m):
    return Matrix(((m[0], m[4], m[8],  m[12]), (m[1], m[5], m[9],  m[13]),
                   (m[2], m[6], m[10], m[14]), (m[3], m[7], m[11], m[15])))

def sample(kfs, t, quat):
    if t <= kfs[0][0]: return Quaternion(kfs[0][1]) if quat else Vector(kfs[0][1])
    if t >= kfs[-1][0]: return Quaternion(kfs[-1][1]) if quat else Vector(kfs[-1][1])
    for lo, hi in zip(kfs, kfs[1:]):
        if lo[0] <= t <= hi[0]:
            f = (t-lo[0])/(hi[0]-lo[0]) if hi[0] != lo[0] else 0.0
            if quat: return Quaternion(lo[1]).slerp(Quaternion(hi[1]), f)
            return Vector(lo[1]).lerp(Vector(hi[1]), f)
    return Quaternion(kfs[-1][1]) if quat else Vector(kfs[-1][1])

def local_world(t):
    W = [None]*len(BONES)
    for i, b in enumerate(BONES):
        L = to_mat(b["local"])
        if t is not None and (i in ROT_TRACKS or i in TRANS_TRACKS):
            trans = L.to_translation(); rot = L.to_3x3()
            if i in ROT_TRACKS:   rot   = sample(ROT_TRACKS[i], t, True).to_matrix()
            if i in TRANS_TRACKS: trans = sample(TRANS_TRACKS[i], t, False)
            L = Matrix.Translation(trans) @ rot.to_4x4()
        p = b["parent"]
        W[i] = L if p < 0 else W[p] @ L
    return W

def build():
    arm = bpy.data.armatures.new("rig"); ao = bpy.data.objects.new("rig", arm)
    bpy.context.collection.objects.link(ao); bpy.context.view_layer.objects.active = ao
    RW = local_world(None)
    bpy.ops.object.mode_set(mode='EDIT'); eb = {}
    for i, b in enumerate(BONES):
        bone = arm.edit_bones.new(b["name"]); eb[i] = bone
        h = (UP @ RW[i]).to_translation(); bone.head = h; bone.tail = h + Vector((0, 0, 0.5))
    for i, b in enumerate(BONES):
        if b["parent"] >= 0: eb[i].parent = eb[b["parent"]]
    for i, b in enumerate(BONES):
        kids = [eb[j] for j, bb in enumerate(BONES) if bb["parent"] == i]
        if kids and (kids[0].head - eb[i].head).length > 1e-3:   # avoid zero-length (Blender deletes those)
            eb[i].tail = kids[0].head
    bpy.ops.object.mode_set(mode='OBJECT')

    for M in MESHES:
        me = bpy.data.meshes.new(M["name"])
        me.from_pydata([list(UP @ Vector(v)) for v in M["verts"]], [], M["tris"]); me.update()
        mo = bpy.data.objects.new(M["name"], me); bpy.context.collection.objects.link(mo)
        md = mo.modifiers.new("arm", 'ARMATURE'); md.object = ao; mo.parent = ao
        vg = {}
        for vi, ws in enumerate(M["weights"]):
            for bi, w in ws:
                g = vg.get(bi)
                if g is None: g = mo.vertex_groups.new(name=BONES[bi]["name"]); vg[bi] = g
                g.add([vi], w, 'REPLACE')
    print("built native rig + %d meshes with authored weights" % len(MESHES))

    for pb in ao.pose.bones: pb.rotation_mode = 'QUATERNION'
    restM = [ao.data.bones[b["name"]].matrix_local.copy() for b in BONES]
    GR = local_world(None)
    ao.animation_data_create(); acts = []
    for mi, (s, e, label) in enumerate(KEYS):
        act = bpy.data.actions.new(f"m{mi}_{label}_{s}-{e}"); act.use_fake_user = True; acts.append((act, e-s))
        ao.animation_data.action = act
        for t in range(s, e+1):
            GW = local_world(t)
            pose = [ (UP @ (GW[i] @ GR[i].inverted()) @ UP.inverted()) @ restM[i] for i in range(len(BONES)) ]
            for i, b in enumerate(BONES):
                p = b["parent"]
                rp = restM[p] if p >= 0 else I4; pp = pose[p] if p >= 0 else I4
                basis = restM[i].inverted() @ rp @ pp.inverted() @ pose[i]
                loc, quat, _ = basis.decompose()
                pbn = ao.pose.bones[b["name"]]; pbn.location = loc; pbn.rotation_quaternion = quat
                pbn.keyframe_insert("location", frame=t-s); pbn.keyframe_insert("rotation_quaternion", frame=t-s)
        ao.animation_data.action = None
    default = len(acts)-1
    act, length = acts[default]
    ao.animation_data.action = act
    bpy.context.scene.frame_start = 0; bpy.context.scene.frame_end = length
    bpy.context.scene.frame_set(length // 2)
    print(f"baked {len(acts)} native motions; showing '{act.name}' mid-motion. Scrub or pick another action.")

build()
'''

if __name__ == "__main__":
    main()
