#!/usr/bin/env python3
"""Blender skeleton COMPARISON: emit one self-contained Blender script that lays out every DC1 fish's
skeleton + its own body mesh in a row (labeled), with Priscleen's mesh at the end, so you can eyeball which
donor skeleton best matches Priscleen's anatomy (spine + mouth + 2 fins). Static (no motions) — this is for
choosing a donor; use build_blender_rig.py on the chosen one to view/weight with motions.

Usage: python3 dc2/build_blender_compare.py   ->  dc2/blender/compare_all.py
"""
import os, sys, struct, re
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "tools"))
from extract_scene_mesh import load_scene, parse_mds, read_tris
from build_blender_rig import parse_chr, skeleton

FISH = ["f00s", "f01a", "f02a", "f03a", "f04a", "f05a", "f06a", "f07a", "f08a",
        "f10a", "f11a", "f12a", "f13a", "f14a", "f15a", "f16a", "f17a", "f18a"]
PRIS = "/Users/thomascantwell/ROMs/dc2_extracted/priscleen/f19a.chr"
OUT = os.path.join(os.path.dirname(__file__), "blender", "compare_all.py")
SPACING = 45.0     # X gap between fish in the row

def body_mesh(mds, alloc_name):
    """verts+tris of the ALLOC_DBUFF (body) mesh node."""
    mo = next((mo for nm, mo, _ in parse_mds(mds, 0) if nm == alloc_name), None)
    if mo is None: return [], []
    vc = struct.unpack_from("<I", mds, mo+0xc)[0]; vo = mo + struct.unpack_from("<I", mds, mo+0x10)[0]
    verts = [list(struct.unpack_from("<3f", mds, vo+i*0x10)) for i in range(vc)]
    return verts, [list(t) for t in read_tris(mds, mo)]

def main():
    entries = []
    for fn in FISH:
        try: d = dict(parse_chr(load_scene(f"chara/{fn}.chr")))
        except Exception: continue
        mds = d[f"{fn}.mds"]; cfg = d["info.cfg"].decode("shift_jis", "replace")
        alloc = re.findall(r'ALLOC_DBUFF\s+"([^"]+)"', cfg)
        frames, world = skeleton(mds)
        bones = [{"name": f"{i}", "parent": pa, "pos": [world[i][12], world[i][13], world[i][14]]}
                 for i, (nm, pa, loc) in enumerate(frames)]
        verts, tris = body_mesh(mds, alloc[0]) if alloc else ([], [])
        entries.append({"name": fn, "bones": bones, "verts": verts, "tris": tris})
    # Priscleen mesh (no skeleton — it's what we're fitting)
    pmds = dict(parse_chr(open(PRIS, "rb").read()))["f19a.mds"]
    pv, pt = body_mesh(pmds, "skin1")
    entries.append({"name": "PRISCLEEN", "bones": [], "verts": pv, "tris": pt})

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("# AUTO-GENERATED by dc2/build_blender_compare.py — open in Blender and Run.\n")
        f.write("# Lays out every DC1 fish skeleton + mesh in a row + Priscleen, to compare skeleton fit.\n")
        f.write("import bpy, math\nfrom mathutils import Vector, Matrix\n\n")
        f.write("SPACING = %r\n" % SPACING)
        f.write("FISH = %r\n" % entries)
        f.write(BODY)
    nb = sum(len(e["bones"]) for e in entries)
    print(f"wrote {OUT}: {len(entries)} fish, {nb} bones total")

BODY = r'''
UP = Matrix.Rotation(math.radians(90), 4, 'X')

def label(text, loc):
    cu = bpy.data.curves.new(text, 'FONT'); cu.body = text; cu.size = 4.0
    ob = bpy.data.objects.new("lbl_"+text, cu); bpy.context.collection.objects.link(ob)
    ob.location = loc

def build(entry, xoff):
    off = Vector((xoff, 0, 0))
    if entry["bones"]:
        arm = bpy.data.armatures.new(entry["name"]); ao = bpy.data.objects.new(entry["name"]+"_rig", arm)
        bpy.context.collection.objects.link(ao); bpy.context.view_layer.objects.active = ao
        bpy.ops.object.mode_set(mode='EDIT'); eb = {}
        for i, b in enumerate(entry["bones"]):
            bone = arm.edit_bones.new(entry["name"]+"_"+b["name"]); eb[i] = bone
            h = UP @ Vector(b["pos"]) + off; bone.head = h; bone.tail = h + Vector((0, 0, 0.4))
        for i, b in enumerate(entry["bones"]):
            if b["parent"] >= 0: eb[i].parent = eb[b["parent"]]
        for i, b in enumerate(entry["bones"]):
            kids = [eb[j] for j, bb in enumerate(entry["bones"]) if bb["parent"] == i]
            if kids: eb[i].tail = kids[0].head
        bpy.ops.object.mode_set(mode='OBJECT')
        ao.show_in_front = True
    if entry["verts"]:
        me = bpy.data.meshes.new(entry["name"]+"_mesh")
        me.from_pydata([list(UP @ Vector(v) + off) for v in entry["verts"]], [], entry["tris"]); me.update()
        mo = bpy.data.objects.new(entry["name"]+"_mesh", me); bpy.context.collection.objects.link(mo)
        mo.display_type = 'WIRE'    # wireframe so the skeleton inside stays visible
    label(entry["name"], off + Vector((0, 0, 16)))

for idx, e in enumerate(FISH):
    build(e, idx * SPACING)
print("Built", len(FISH), "fish for comparison (wireframe meshes; armatures shown in front).")
'''

if __name__ == "__main__":
    main()
