#!/usr/bin/env python3
"""Emit a Blender script showing Priscleen's OWN DC2 rig with APPROXIMATE DC1-style motions.

build_priscleen_native.py shows the 3 real DC2 motions (which look fine alone but don't match DC1's
animation style). This script instead uses Priscleen's native skeleton + native weights + both body
meshes (skin1 = body, skin2 = fin membranes), and PROCEDURALLY authors the 7 DC1 fish motions on
those bones:

    0 通常 normal swim   1 バトル元気 battle-energetic   2 バトル弱気 battle-timid
    3 飛びはね leap       4 釣り上げられ中 being-reeled    5 釣り上げられた caught/flop
    6 アイドリング idle

The motions are built from anatomy, not retargeted from a donor skeleton (that path stretched the
mesh). Each is a set of world-axis rotations — a traveling yaw wave down the spine (swim), up/down fin
flaps, a jaw gasp, and a body pitch for the hanging poses — converted into each bone's local frame and
baked through the SAME matrix pipeline the native script uses, so the mesh sits correctly on the rig.

Everything is tunable: the MP (motion-params) table and the tuning constants live at the top of the
generated Blender file — tweak amplitudes/frequencies there and re-run in Blender, no regen needed.

Source: DC2 sg/fish/f19a.chr. Output: dc2/blender/priscleen_dc1motions.py
"""
import os, sys, struct
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "tools"))
from dc2_archive import read_file
from build_blender_rig import parse_chr, skeleton
from build_priscleen_native import mesh_of, parse_wgt

OUT = os.path.join(os.path.dirname(__file__), "blender", "priscleen_dc1motions.py")

def subtree(parent, root):
    """All bone indices in the subtree rooted at `root` (inclusive)."""
    out, stack = [], [root]
    while stack:
        i = stack.pop(); out.append(i)
        stack += [j for j, p in enumerate(parent) if p == i]
    return sorted(out)

def main():
    chr = dict(parse_chr(read_file("sg/fish/f19a.chr")))
    mds = chr["f19a.mds"]
    frames, world = skeleton(mds)
    parent = [pa for (_, pa, _) in frames]
    bones = [{"name": f"{i}_{nm}", "parent": pa, "local": loc} for i, (nm, pa, loc) in enumerate(frames)]
    wmap = parse_wgt(chr["f19a.wgt"], frames)

    meshes = []
    for mname in ("skin1", "skin2"):
        verts, tris = mesh_of(mds, mname)
        w = wmap.get(mname, {})
        meshes.append({"name": mname, "verts": verts, "tris": tris,
                       "weights": [w.get(vi, []) for vi in range(len(verts))]})

    # Anatomy groups by subtree (see docstring / bone map). Tail excludes the pelvic-fin subtrees.
    tail = [i for i in subtree(parent, 27) if i not in subtree(parent, 42) + subtree(parent, 45)]
    groups = {
        "SPINE":   tail,                       # 27..41  traveling yaw wave (swim)
        "NECK":    [5, 6],                      # neck joints — swing the nose for the front of the S-curve
        "DORSAL":  subtree(parent, 23),        # 23..25  upper fin (rudder sway)
        "PECT_R":  subtree(parent, 17),        # 17..22  +X pectoral
        "PECT_L":  subtree(parent, 11),        # 11..16  -X pectoral
        "PELV_R":  subtree(parent, 45),        # 45..47  +X pelvic
        "PELV_L":  subtree(parent, 42),        # 42..44  -X pelvic
        "JAW":     subtree(parent, 8),         # 8..10   lower mouth (gasp)
        "NOSE":    [26],                       # upper mouth / snout
        "BODY":    [1],                        # whole-fish pitch pivot
    }

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("# AUTO-GENERATED by dc2/build_priscleen_dc1motions.py — Priscleen's native rig, DC1-style motions.\n")
        f.write("# Open in Blender's Text editor and Run. Tune the MP table + constants near the top of BODY.\n")
        f.write("import bpy, math\nfrom mathutils import Vector, Quaternion, Matrix\n\n")
        f.write("BONES  = %r\n" % bones)
        f.write("MESHES = %r\n" % meshes)
        f.write("GROUPS = %r\n" % groups)
        f.write(BODY)
    print(f"wrote {OUT}: {len(bones)} bones, {len(meshes)} meshes, "
          f"groups spine={len(tail)} pectR={len(groups['PECT_R'])} pelvR={len(groups['PELV_R'])} "
          f"dorsal={len(groups['DORSAL'])} jaw={len(groups['JAW'])}")

BODY = r'''
# ============================================================================================
# TUNING — edit freely, re-run (File > New, paste/open, Run). All amplitudes in DEGREES.
# Per-motion: len (frames), loop, body (tail-tip yaw), bfreq (body cycles), fin (flap amp),
#   ffreq (fin cycles), jaw (mouth open), pitch (static nose-up), arc (leap pitch arc), wob (erratic).
# `len` = keyframe count-1; matched to DC1 frame counts from f00s (the only 7-distinct-motion fish;
#   its named slots map 1:1 to these). Regular fish (f07a/f08a — Priscleen's topology match) reuse
#   just slots 0/1/6. Loop motions use whole-number freqs so the seam is clean.
# ============================================================================================
MP = {
    "0_normal 通常 15f":   dict(len=14, loop=True,  body=40, bfreq=1.0, fin=12, ffreq=1.0, jaw=4,  pect=38, prow=9, pitch=0, arc=0, wob=0),
    "1_battle元気 15f":    dict(len=14, loop=True,  body=40, bfreq=1.0, fin=12, ffreq=1.0, jaw=4,  pect=70, prow=5, pitch=0, arc=0, wob=0),
    "2_battle弱気 21f":    dict(len=20, loop=True,  body=16, bfreq=1.0, fin=8,  ffreq=1.0, jaw=3,  pect=48, prow=9, pitch=0, arc=0, wob=0),
    "3_leap 飛びはね 21f": dict(len=20, loop=False, body=50, bfreq=1.0, fin=30, ffreq=2.0, jaw=6,  pect=60, prow=9, pitch=0, arc=0, wob=0),
    "4_reeled 釣中 21f":   dict(len=20, loop=True,  body=26, bfreq=3.0, fin=32, ffreq=3.0, jaw=11, pect=55, prow=9, pitch=0, arc=0, wob=16),
    "5_caught 釣れた 21f": dict(len=20, loop=True,  body=15, bfreq=1.0, fin=6,  ffreq=1.0, jaw=15, pect=42, prow=9, pitch=0, arc=0, wob=9),
    "6_idle アイドル 15f": dict(len=14, loop=True,  body=8,  bfreq=1.0, fin=5,  ffreq=1.0, jaw=2,  pect=38, prow=9, pitch=0, arc=0, wob=0),
}
# pect = pectoral sweep-back (deg), prow = pectoral row amplitude (deg, 2x-rate fore/aft stroke)
# --- carangiform spine wave (tuned to f00s motion 0: pivots on a fixed nose, tail whips ~19u; no tilt) ---
WAVE_K = 0.22           # phase travel down the body (rad per game-unit): drives the traveling S-node
SPINE_BASE_FRAC = 0.16  # anterior-body floor of the tail wave (the nose pivot below adds the front swing)
SPINE_POWER = 1.0       # tail-weighting exponent (higher = motion concentrated further back)
BODY_PHASE = 2.25       # rad: start-of-loop phase — aligned so Priscleen swings the SAME way as f00s
PIVOT_NOSE = 7          # deg: whole body yaws about the FIXED nose point — f00s "pivots on its nose"
DORSAL_FOLLOW = 0.25    # dorsal fin sways this fraction of the body amp (acts as a rudder)
PECT_DROOP = 25         # pectoral fins angled downward (deg at the fin base, static rest pose)
                        # (pectoral sweep-back MP[...]["pect"] and row amplitude MP[...]["prow"] are per-motion)

# Game-space axes (Y up, Z fore/aft with the fish facing +Z, X left/right).
UPv, RIGHT, FWD = Vector((0, 1, 0)), Vector((1, 0, 0)), Vector((0, 0, 1))
TAU = math.tau

# ============================================================================================
UP = Matrix.Rotation(math.radians(90), 4, 'X')     # game Y-up -> Blender Z-up
I4 = Matrix.Identity(4)

def to_mat(m):
    return Matrix(((m[0], m[4], m[8],  m[12]), (m[1], m[5], m[9],  m[13]),
                   (m[2], m[6], m[10], m[14]), (m[3], m[7], m[11], m[15])))

REST_L = [to_mat(b["local"]) for b in BONES]

def rest_world():
    W = [None] * len(BONES)
    for i, b in enumerate(BONES):
        p = b["parent"]
        W[i] = REST_L[i] if p < 0 else W[p] @ REST_L[i]
    return W

GR = rest_world()                                  # rest game-world per bone
GZ = [GR[i].to_translation().z for i in range(len(BONES))]   # rest fore/aft position

# spine wave geometry: front->tail axis + per-Z-station joint multiplicity. Coincident jnt/eff bones
# share a station; splitting the bend among them keeps the envelope independent of joint count.
_SP = GROUPS["SPINE"]
SP_Z0 = GZ[_SP[0]]; SP_SPAN = GZ[_SP[-1]] - GZ[_SP[0]]
SP_MULT = {i: sum(1 for j in _SP if round(GZ[j], 1) == round(GZ[i], 1)) for i in _SP}
NOSE_N = GR[GROUPS["NOSE"][0]].to_translation()   # rest world position of the nose (the pivot point)

def game_world(deltas, pivot_deg=0.0):
    """Rebuild game-world matrices with per-bone LOCAL rotation deltas (identity where absent).
    pivot_deg yaws the WHOLE fish about the fixed nose point (game Y-up) — f00s 'pivots on its nose'."""
    W = [None] * len(BONES)
    for i, b in enumerate(BONES):
        L = REST_L[i]
        d = deltas.get(i)
        if d is not None:
            L = Matrix.Translation(L.to_translation()) @ (L.to_3x3() @ d.to_matrix()).to_4x4()
        p = b["parent"]
        W[i] = L if p < 0 else W[p] @ L
    if abs(pivot_deg) > 1e-6:                        # rigid yaw about the nose: anchor there, body swings
        T = Matrix.Translation(NOSE_N) @ Matrix.Rotation(math.radians(pivot_deg), 4, 'Y') @ Matrix.Translation(-NOSE_N)
        W = [T @ w for w in W]
    return W

def wq(i, axis, deg):
    """Quaternion (bone-LOCAL frame) that rotates bone i about a GAME-WORLD axis by deg."""
    a = GR[i].to_3x3().inverted() @ axis
    return Quaternion(a, math.radians(deg))

def add(d, i, axis, deg):
    if abs(deg) < 1e-6: return
    q = wq(i, axis, deg)
    d[i] = (d[i] @ q) if i in d else q

def deltas(mp, t):
    """Local-frame rotation deltas for every animated bone at frame t (0..len)."""
    d = {}
    prog = t / mp["len"] if mp["len"] else 0.0
    # ---- spine: carangiform traveling yaw wave — stiff front, tail whip (tuned to f00s motion 0) ----
    for i in GROUPS["SPINE"]:
        u = (GZ[i] - SP_Z0) / SP_SPAN if SP_SPAN else 0.0        # 0 at front of body, 1 at tail tip
        A = mp["body"] * (SPINE_BASE_FRAC + (1 - SPINE_BASE_FRAC) * u ** SPINE_POWER)
        ph = TAU * mp["bfreq"] * prog + BODY_PHASE - WAVE_K * (SP_Z0 - GZ[i])
        ang = A / SP_MULT[i] * math.sin(ph)         # split the station's bend among coincident joints
        if mp["wob"]:                               # deterministic pseudo-noise for the struggle
            ang += (mp["wob"] / SP_MULT[i]) * math.sin(6.3 * TAU * prog + 0.9 * i)
        add(d, i, UPv, ang)
    # (the anterior/nose swing is handled by the whole-body PIVOT_NOSE yaw in game_world, not here)
    # ---- dorsal fin: gentle rudder sway following the body ----------------------------------
    for i in GROUPS["DORSAL"]:
        add(d, i, UPv, DORSAL_FOLLOW * mp["body"] / max(len(GROUPS["DORSAL"]), 1)
                        * math.sin(TAU * mp["bfreq"] * prog + BODY_PHASE))
    # ---- fins: pectorals row front-to-back (sweep oscillates); pelvics flap up/down -------
    fin = math.sin(TAU * mp["ffreq"] * prog)
    row = math.sin(TAU * 2 * mp["bfreq"] * prog + BODY_PHASE)  # 2x body rate: one stroke per tail-swing direction
    for name, sign in (("PECT_R", +1), ("PECT_L", -1), ("PELV_R", +1), ("PELV_L", -1)):
        g = GROUPS[name]; n = max(len(g), 1)
        if name.startswith("PECT"):                    # whole-fin pose at the base: swept back + drooped
            base = g[0]
            add(d, base, UPv, sign * mp["pect"])        # per-motion sweep (calmer motions less back)
            add(d, base, FWD, -sign * PECT_DROOP)       # drooped down
            add(d, base, UPv, sign * mp["prow"] * row)  # ROW: fore/aft, once per tail-swing direction (2x rate)
        else:                                          # pelvics: flap distributed along the fin
            amp = sign * mp["fin"] / n
            w = fin
            if mp["wob"]:
                w += 0.5 * math.sin(5.1 * TAU * prog + hash(name) % 7)
            for i in g:
                add(d, i, FWD, amp * w)
    # ---- jaw gasp: pitch open about the left/right axis (0 -> jaw) --------------------------
    openf = 0.5 - 0.5 * math.cos(TAU * mp["ffreq"] * prog)
    for i in GROUPS["JAW"]:
        add(d, i, RIGHT, -mp["jaw"] * openf / max(len(GROUPS["JAW"]), 1))
    # ---- whole-body pitch: static hang (reeled/caught) + leap arc --------------------------
    pitch = mp["pitch"]
    if mp["arc"]:
        pitch += mp["arc"] * math.sin(math.pi * prog)     # rise-and-fall leap
    add(d, GROUPS["BODY"][0], RIGHT, pitch)
    return d

def build():
    arm = bpy.data.armatures.new("rig"); ao = bpy.data.objects.new("rig", arm)
    bpy.context.collection.objects.link(ao); bpy.context.view_layer.objects.active = ao
    bpy.ops.object.mode_set(mode='EDIT'); eb = {}
    for i, b in enumerate(BONES):
        bone = arm.edit_bones.new(b["name"]); eb[i] = bone
        h = (UP @ GR[i]).to_translation(); bone.head = h; bone.tail = h + Vector((0, 0, 0.5))
    for i, b in enumerate(BONES):
        if b["parent"] >= 0: eb[i].parent = eb[b["parent"]]
    for i, b in enumerate(BONES):
        kids = [eb[j] for j, bb in enumerate(BONES) if bb["parent"] == i]
        if kids and (kids[0].head - eb[i].head).length > 1e-3:   # zero-length bones get deleted by Blender
            eb[i].tail = kids[0].head
    bpy.ops.object.mode_set(mode='OBJECT')

    for M in MESHES:
        me = bpy.data.meshes.new(M["name"])
        me.from_pydata([list(UP @ Vector(v)) for v in M["verts"]], [], M["tris"]); me.update()
        mo = bpy.data.objects.new(M["name"], me); bpy.context.collection.objects.link(mo)
        md = mo.modifiers.new("arm", 'ARMATURE'); md.object = ao; mo.parent = ao
        vg = {}
        for vi, ws in enumerate(M["weights"]):
            for bi, w in ws:
                g = vg.get(bi)
                if g is None: g = mo.vertex_groups.new(name=BONES[bi]["name"]); vg[bi] = g
                g.add([vi], w, 'REPLACE')
    print("built native rig + %d meshes with authored weights" % len(MESHES))

    for pb in ao.pose.bones: pb.rotation_mode = 'QUATERNION'
    restM = [ao.data.bones[b["name"]].matrix_local.copy() for b in BONES]
    ao.animation_data_create(); acts = []
    for name, mp in MP.items():
        act = bpy.data.actions.new(name); act.use_fake_user = True; acts.append((act, mp["len"]))
        act.use_frame_range = True; act.frame_start = 0; act.frame_end = mp["len"]   # per-motion end frame
        act.use_cyclic = mp["loop"]
        ao.animation_data.action = act
        for t in range(0, mp["len"] + 1):
            prog = t / mp["len"] if mp["len"] else 0.0
            pivot_deg = PIVOT_NOSE * math.sin(TAU * mp["bfreq"] * prog + BODY_PHASE)   # swings about the fixed nose
            GW = game_world(deltas(mp, t), pivot_deg)
            pose = [(UP @ (GW[i] @ GR[i].inverted()) @ UP.inverted()) @ restM[i] for i in range(len(BONES))]
            for i, b in enumerate(BONES):
                p = b["parent"]
                rp = restM[p] if p >= 0 else I4; pp = pose[p] if p >= 0 else I4
                basis = restM[i].inverted() @ rp @ pp.inverted() @ pose[i]
                loc, quat, _ = basis.decompose()
                pbn = ao.pose.bones[b["name"]]; pbn.location = loc; pbn.rotation_quaternion = quat
                pbn.keyframe_insert("location", frame=t); pbn.keyframe_insert("rotation_quaternion", frame=t)
        ao.animation_data.action = None
    install_sync()                                  # make the timeline follow the active action's range
    act, length = acts[0]                           # show the normal swim by default
    ao.animation_data.action = act
    bpy.context.scene.frame_start = 0; bpy.context.scene.frame_end = length
    bpy.context.scene.frame_set(0)
    print(f"baked {len(acts)} DC1-style motions: " + ", ".join(a.name for a, _ in acts))
    print("Pick a motion in the Action editor / dope sheet; the timeline end follows it. Space to play.")

def _sync_action_range(scene, depsgraph=None):
    """Keep the scene play range == the active action's own frame range, so switching motions in the
    Action editor updates the timeline end automatically."""
    try:
        ao = bpy.data.objects.get("rig")
        act = getattr(getattr(ao, "animation_data", None), "action", None)
        if act and act.use_frame_range:
            s, e = int(act.frame_start), int(act.frame_end)
            if scene.frame_start != s or scene.frame_end != e:
                scene.frame_start, scene.frame_end = s, e
    except Exception:
        pass

def install_sync():
    hs = bpy.app.handlers.depsgraph_update_post
    hs[:] = [h for h in hs if getattr(h, "__name__", "") != "_sync_action_range"]
    hs.append(_sync_action_range)

build()
'''

if __name__ == "__main__":
    main()
