#!/usr/bin/env python3
"""Emit a Blender script that builds f00s's NATIVE DC1 rig + mesh + all 7 real motions, offset beside
Priscleen so the procedural DC1-style motions can be compared against the genuine article.

f00s is the only DC1 fish with 7 truly distinct animation clips (通常 / バトル元気 / バトル弱気 /
飛びはね / 釣り上げられ中 / 釣り上げられた / アイドリング) — every other fish repeats an idle across
the spare slots. This is the reference the procedural motions in build_priscleen_dc1motions.py were
timed against (its 15/15/21/21/21/21/15 frame counts).

Run priscleen_dc1motions.py first, then this in the SAME Blender file: distinct object names
("f00s_rig"/"f00s_skin") and an +X object offset keep it clear of Priscleen. Same bake pipeline +
quaternion conjugation as the native script, so it deforms correctly on f00s's own skeleton.

Source: DC1 chara/f00s.chr. Output: dc2/blender/f00s_compare.py
"""
import os, sys, struct, re
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "tools"))
from extract_scene_mesh import load_scene
from build_blender_rig import parse_chr, skeleton, motions
from build_priscleen_native import mesh_of, parse_wgt

OUT = os.path.join(os.path.dirname(__file__), "blender", "f00s_compare.py")
OFFSET_X = 45.0     # Blender-X gap so f00s sits clear of Priscleen at the origin

def main():
    chr = dict(parse_chr(load_scene("chara/f00s.chr")))
    mds = chr["f00s.mds"]; cfg = chr["info.cfg"].decode("shift_jis", "replace")
    frames, world = skeleton(mds)
    bones = [{"name": f"{i}_{nm}", "parent": pa, "local": loc} for i, (nm, pa, loc) in enumerate(frames)]

    verts, tris = mesh_of(mds, "skin")
    w = parse_wgt(chr["f00s.wgt"], frames).get("skin", {})
    mesh = {"name": "f00s_skin", "verts": verts, "tris": tris,
            "weights": [w.get(vi, []) for vi in range(len(verts))]}

    _, rot, trans = motions(chr["f00s.mot"], cfg)
    labels = ["0_通常", "1_バトル元気", "2_バトル弱気", "3_飛びはね", "4_釣中", "5_釣れた", "6_アイドル"]
    ks = re.findall(r'KEY\s+(\d+)\s*,\s*(\d+)', cfg)
    seen, keys = set(), []
    for i, (s, e) in enumerate(ks):                    # keep the 7 slots but drop duplicate ranges
        s, e = int(s), int(e)
        if (s, e) in seen: continue
        seen.add((s, e)); keys.append((s, e, labels[i] if i < len(labels) else f"slot{i}"))

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("# AUTO-GENERATED by dc2/build_f00s_compare.py — genuine DC1 f00s rig + 7 real motions.\n")
        f.write("# Run priscleen_dc1motions.py first, then this, in the same Blender file to compare.\n")
        f.write("import bpy, math\nfrom mathutils import Vector, Quaternion, Matrix\n\n")
        f.write("OFFSET_X = %r\n" % OFFSET_X)
        f.write("BONES  = %r\n" % bones)
        f.write("MESH   = %r\n" % mesh)
        f.write("KEYS   = %r\n" % keys)
        # DC .mot quaternions use the opposite handedness from mathutils — conjugate (same fix the
        # native script needed so the mesh reproduces the .mds/.bbp bind).
        f.write("ROT_TRACKS   = %r\n" % {k: [(t, [q[0], -q[1], -q[2], -q[3]]) for t, q in v] for k, v in rot.items()})
        f.write("TRANS_TRACKS = %r\n" % {k: [(t, list(q)) for t, q in v] for k, v in trans.items()})
        f.write(BODY)
    print(f"wrote {OUT}: {len(bones)} bones, {len(verts)}v mesh, {len(keys)} distinct motions "
          f"({len(rot)} rot / {len(trans)} trans tracks)")

BODY = r'''
UP = Matrix.Rotation(math.radians(90), 4, 'X')
I4 = Matrix.Identity(4)

def to_mat(m):
    return Matrix(((m[0], m[4], m[8],  m[12]), (m[1], m[5], m[9],  m[13]),
                   (m[2], m[6], m[10], m[14]), (m[3], m[7], m[11], m[15])))

def sample(kfs, t, quat):
    if t <= kfs[0][0]: return Quaternion(kfs[0][1]) if quat else Vector(kfs[0][1])
    if t >= kfs[-1][0]: return Quaternion(kfs[-1][1]) if quat else Vector(kfs[-1][1])
    for lo, hi in zip(kfs, kfs[1:]):
        if lo[0] <= t <= hi[0]:
            f = (t-lo[0])/(hi[0]-lo[0]) if hi[0] != lo[0] else 0.0
            if quat: return Quaternion(lo[1]).slerp(Quaternion(hi[1]), f)
            return Vector(lo[1]).lerp(Vector(hi[1]), f)
    return Quaternion(kfs[-1][1]) if quat else Vector(kfs[-1][1])

def local_world(t):
    W = [None]*len(BONES)
    for i, b in enumerate(BONES):
        L = to_mat(b["local"])
        if t is not None and (i in ROT_TRACKS or i in TRANS_TRACKS):
            trans = L.to_translation(); rot = L.to_3x3()
            if i in ROT_TRACKS:   rot   = sample(ROT_TRACKS[i], t, True).to_matrix()
            if i in TRANS_TRACKS: trans = sample(TRANS_TRACKS[i], t, False)
            L = Matrix.Translation(trans) @ rot.to_4x4()
        p = b["parent"]
        W[i] = L if p < 0 else W[p] @ L
    return W

def build():
    arm = bpy.data.armatures.new("f00s_rig"); ao = bpy.data.objects.new("f00s_rig", arm)
    bpy.context.collection.objects.link(ao); bpy.context.view_layer.objects.active = ao
    RW = local_world(None)
    bpy.ops.object.mode_set(mode='EDIT'); eb = {}
    for i, b in enumerate(BONES):
        bone = arm.edit_bones.new(b["name"]); eb[i] = bone
        h = (UP @ RW[i]).to_translation(); bone.head = h; bone.tail = h + Vector((0, 0, 0.5))
    for i, b in enumerate(BONES):
        if b["parent"] >= 0: eb[i].parent = eb[b["parent"]]
    for i, b in enumerate(BONES):
        kids = [eb[j] for j, bb in enumerate(BONES) if bb["parent"] == i]
        if kids and (kids[0].head - eb[i].head).length > 1e-3:
            eb[i].tail = kids[0].head
    bpy.ops.object.mode_set(mode='OBJECT')

    me = bpy.data.meshes.new(MESH["name"])
    me.from_pydata([list(UP @ Vector(v)) for v in MESH["verts"]], [], MESH["tris"]); me.update()
    mo = bpy.data.objects.new(MESH["name"], me); bpy.context.collection.objects.link(mo)
    md = mo.modifiers.new("arm", 'ARMATURE'); md.object = ao; mo.parent = ao
    vg = {}
    for vi, ws in enumerate(MESH["weights"]):
        for bi, wt in ws:
            g = vg.get(bi)
            if g is None: g = mo.vertex_groups.new(name=BONES[bi]["name"]); vg[bi] = g
            g.add([vi], wt, 'REPLACE')

    for pb in ao.pose.bones: pb.rotation_mode = 'QUATERNION'
    restM = [ao.data.bones[b["name"]].matrix_local.copy() for b in BONES]
    GR = local_world(None)
    ao.animation_data_create(); acts = []
    for (s, e, label) in KEYS:
        act = bpy.data.actions.new(f"f00s_{label}_{s}-{e}"); act.use_fake_user = True
        act.use_frame_range = True; act.frame_start = 0; act.frame_end = e - s
        acts.append((act, e - s))
        ao.animation_data.action = act
        for t in range(s, e+1):
            GW = local_world(t)
            pose = [(UP @ (GW[i] @ GR[i].inverted()) @ UP.inverted()) @ restM[i] for i in range(len(BONES))]
            for i, b in enumerate(BONES):
                p = b["parent"]
                rp = restM[p] if p >= 0 else I4; pp = pose[p] if p >= 0 else I4
                basis = restM[i].inverted() @ rp @ pp.inverted() @ pose[i]
                loc, quat, _ = basis.decompose()
                pbn = ao.pose.bones[b["name"]]; pbn.location = loc; pbn.rotation_quaternion = quat
                pbn.keyframe_insert("location", frame=t-s); pbn.keyframe_insert("rotation_quaternion", frame=t-s)
        ao.animation_data.action = None

    ao.location.x = OFFSET_X                      # shift the whole f00s object clear of Priscleen
    act, length = acts[0]
    ao.animation_data.action = act
    print(f"built f00s: {len(acts)} real motions offset +{OFFSET_X} in X — " + ", ".join(a.name for a, _ in acts))
    print("Select f00s_rig (or Priscleen's rig) + its action to compare a motion. Space to play.")

build()
'''

if __name__ == "__main__":
    main()
