#!/usr/bin/env python3
"""Generate GameData/EnemyGuardMotions.cs — every species' IDLE, first DAMAGE (stagger) and GUARD motions (raise clip
+ hold loop), read from docs/enemy-motion-table.md, for abilities that put an enemy through its own clips (Sun Sword
"Solar Flash": stagger → guard, or stagger → idle for a species without a guard).

The motion table is the decoded KEY block of each monster .chr (see tools/analysis/augment_motion_table.py); a species'
guard is the row the model names ガード入り / ガードループ (a few models name only one "guard" clip, which then serves
as both), its stagger the first ダメージ row, its idle the 立ち row (index 0 when unnamed). Guard fields are -1 for a
species without one.

Run from the repo root:  python3 tools/analysis/gen_enemy_guard_motions.py
"""
import re, sys, os

DOC = "docs/enemy-motion-table.md"
OUT = "Dark Cloud Improved Version/GameData/EnemyGuardMotions.cs"

ENTER = {"guard (enter)", "guard(enter)", "guard((enter))"}
LOOP  = {"guard (loop)", "guardﾙｰﾌﾟ"}
LONE  = {"guard"}                                       # a plain "guard" row: the RAISE where a loop row follows it (Auntie Medu:
                                                        # 5 guard, 6 guard-loop, 7 guard-return), else a one-clip guard — enter and hold
RET   = {"guard (return)"}                              # the clip that LOWERS the guard, back to idle
IDLE  = {"idle", "stand", "standing"}
def is_damage(m): return m.startswith("damage") and "(big)" not in m

head = re.compile(r"^### (\d+) — (.+?) `(\w+)`")
row  = re.compile(r"^\| (\d+) \| (\d+)(?:–(\d+))? \| ([\d.]+) \| [^|]* \| ([^|]+) \|$")   # a one-frame row has no range (Statue Dog's guard loop: "100")

species = {}          # tableIndex -> dict(name, code, enter=(idx,s,e,spd), loop=(idx,s,e,spd))
cur = None
for line in open(DOC, encoding="utf-8"):
    m = head.match(line)
    if m:
        cur = {"name": m.group(2).strip(), "code": m.group(3), "enter": None, "loop": None, "ret": None, "idle": None, "damage": None, "lone": None}
        species[int(m.group(1))] = cur
        continue
    if cur is None: continue
    m = row.match(line.rstrip("\n"))
    if not m: continue
    idx, s, e, spd, meaning = int(m.group(1)), int(m.group(2)), int(m.group(3) or m.group(2)), float(m.group(4)), m.group(5).strip()
    if meaning in ENTER and cur["enter"] is None: cur["enter"] = (idx, s, e, spd)
    elif meaning in LOOP and cur["loop"] is None: cur["loop"] = (idx, s, e, spd)
    elif meaning in LONE and cur["lone"] is None: cur["lone"] = (idx, s, e, spd)
    elif meaning in RET and cur["ret"] is None: cur["ret"] = (idx, s, e, spd)
    elif meaning in IDLE and cur["idle"] is None: cur["idle"] = (idx, s, e, spd)
    elif is_damage(meaning) and cur["damage"] is None: cur["damage"] = (idx, s, e, spd)

lines = []
guarded = 0
for ti in sorted(species):
    sp = species[ti]
    enter, loop, idle, dmg, back = sp["enter"], sp["loop"], sp["idle"], sp["damage"], sp["ret"]
    lone = sp["lone"]
    if enter is None: enter = lone or loop   # a plain "guard" raises it; failing that one clip serves as both
    if loop is None:  loop = lone or enter
    if enter is not None: guarded += 1
    ei, es, ee = (enter[0], enter[1], enter[2]) if enter else (-1, 0, 0)
    li, ls, le, lspd = (loop[0], loop[1], loop[2], loop[3]) if loop else (-1, 0, 0, 0.0)
    ii = idle[0] if idle else 0
    di, ds, de = (dmg[0], dmg[1], dmg[2]) if dmg else (-1, 0, 0)
    ri, rs, rr = (back[0], back[1], back[2]) if back else (-1, 0, 0)
    name = sp["name"].replace('"', "'")
    lines.append(f"            [{ti:3d}] = new({ii:2d}, {di:2d}, {ds:3d}, {de:3d}, {ei:2d}, {es:3d}, {ee:3d}, {li:2d}, {ls:3d}, {le:3d}, {ri:2d}, {rs:3d}, {rr:3d}, {lspd:.2f}f),   // {name} {sp['code']}")

src = f'''// <auto-generated> by tools/analysis/gen_enemy_guard_motions.py from docs/enemy-motion-table.md — do not edit by hand. </auto-generated>
using System.Collections.Generic;

namespace Dark_Cloud_Improved_Version
{{
    /// <summary>Every species' idle, first damage (stagger) and guard motions, keyed by species-table index: indices are the
    /// model's motion-table order (the value _SET_MOTION takes), frames the clip's key range, Speed the guard loop's KEY
    /// playback rate. Guard fields are -1 for a species without one (<see cref="Guard.HasGuard"/>), and Return is the clip
    /// that LOWERS the guard back to idle (-1 if the model has none). Read from the decoded
    /// monster motion tables (docs/enemy-motion-table.md) by tools/analysis/gen_enemy_guard_motions.py.</summary>
    internal static class EnemyGuardMotions
    {{
        internal readonly record struct Guard(int Idle, int Damage, int DamageStart, int DamageEnd,
                                              int Enter, int EnterStart, int EnterEnd, int Loop, int LoopStart, int LoopEnd,
                                              int Return, int ReturnStart, int ReturnEnd, float Speed)
        {{
            internal bool HasGuard  => Enter >= 0;
            internal bool HasReturn => Return >= 0;
        }}

        internal static bool TryGet(int tableIndex, out Guard g) => ByTableIndex.TryGetValue(tableIndex, out g);

        internal static readonly Dictionary<int, Guard> ByTableIndex = new()
        {{
{chr(10).join(lines)}
        }};
    }}
}}
'''
open(OUT, "w", encoding="utf-8").write(src)
print(f"{len(lines)} species ({guarded} with a guard clip) → {OUT}")
